### ISSUE TITLE
map AVG problem

### ISSUE THREAD

**Issue by sunbrn** [akaitoua/GMQL#2]
**Query**
EXP = SELECT( dataType == ""ChipSeq"" AND antibody == ""CTCF"" AND cell == ""A549"" ) HG19_ENCODE_BED;
REF = SELECT( annotation_type == ""promoter"" ) HG19_BED_ANNOTATION;
RES = MAP(avg_score AS AVG(score)) REF EXP;
MATERIALIZE EXP into exp;
MATERIALIZE REF into ref;
MATERIALIZE RES into res;

See Image below.
Problem: the avg is not computed correctly. If COUNT=1, AVG is correctly equal to the same value as the score of the only region of the experiment sample. But, if I have two/three regions to be mapped on a ref region, tha avg is lower than expected (paradox: it's lower than the MIN score!)
Please check the formula to compute avg.
[![screenshot 2016-10-11 11 43 31](https://cloud.githubusercontent.com/assets/11488353/19345768/49faa7e6-9140-11e6-9d49-2c9eded7aafe.png)](url)

**Comment by pp86** [comment]
If I understood the problem correctly it should be on @akaitoua
