### ISSUE TITLE
project: region update

### ISSUE THREAD

**Issue by eirinistam** [akaitoua/GMQL#8]
I attached the datasets and a description for them is the below:
Example3:
.gtf
DATA_SET_VAR = SELECT(assay == 'iCLIP') HG19_ENCODE_NARROW_NOV_2016;RES = PROJECT(ALLBUT score; region_update: new_score AS score/100.0 )DATA_SET_VAR;
This GMQL statement supposed to create a new dataset called RES by preserving all region attributes apart from score, and creating a new region attribute called new_score by dividing the existing score value of each region by 1000.0. Instead of this we have different results, in the schema file of RES  exists the attribute score and there is no new_score. In the region file of RES  the column of score is always 0.0 . 

.gdm (the option tab)
We test the same query and dataset but this time the format of the output to be tab . The results are still different from what we expect and from the .gtf format. In the schema file of RES there is no score and new_score , in the region file of RES there is a new column in the end with always the same value -0.01. 
.gtf
DATA_SET_VAR = SELECT(assay == 'iCLIP') HG19_ENCODE_NARROW_JULY_2016;RES = PROJECT(ALLBUT name; region_update: new_score AS score/100.0 )DATA_SET_VAR;

We test with the above query , the new results are that in the schema file there is the attribute score but no the name and the new_score. In the region file of RES the score column has correct values but there is no column for new_score.
.gdm
The same query but this time the format of the output to be tab. In the schema file there is no name and new_score . In the region file there is a new column in the end with the same values always -0.01.

.gtf
DATA_SET_VAR = SELECT(assay == 'iCLIP') HG19_ENCODE_NARROW_JULY_2016;RES = PROJECT(ALLBUT peak; region_update: new_score AS score/100.0 )DATA_SET_VAR;We test with the above query, the new results are that in the schema file there is neither peak nor new_score . .gdm
We test with the above query ant with the tab format, the new results in the schema file , there is no peak and new_score . In the region file at the last column appears the correct result for the new_score.

The files exapmle3 for gtf and tab
https://www.dropbox.com/sh/gio9lnkwjfys68a/AAA0bJ-6cZlUxcCMkYq-nvWya?dl=0
https://www.dropbox.com/sh/iis3ngck2rsiylx/AAAbzZ1oemCGj05v2dKLhPBpa?dl=0

**Comment by pp86** [comment]
My last push should fix this.

**Comment by akaitoua** [comment]
I investigated the -1 output. I found the error because score column is not found. Since you first are deleting the score column from the values, you can not then use score again in the projection. @pp86 , if it should do something different than this, the DAG should be changed first.

**Comment by pp86** [comment]
How is the DAG now and how should it be?

**Comment by akaitoua** [comment]
@pp86 , Two scenarios to be considered: 
- either to do the ALLBUT at first then do the region extension. This will take the "score" off and (from the previous example), and the extend will use wrong index since "score" column is removed.
- or perform the region extension at first, then the ALLBUT. In this case the DAG should be changed in order to send the index of the extra column generated "newScore".

**Comment by akaitoua** [comment]
@pp86, i submitted the changes that makes Project extends the region before performing ALLBUT. commit number a187a99

**Comment by pp86** [comment]
@akaitoua do I have to change anything from my side?

**Comment by akaitoua** [comment]
@pp86 , Yes please.
ProjectRD receives a List of indexes( projectedValues : Option[List[Int]]), you just need to add additional index for the extended column. Since we are now doing columns projection after column extension. 
What is happening now: the extended column is not shown in the result because the projection does not provide its index to keep it.

**Comment by pp86** [comment]
@akaitoua I changed the node parameters accordingly with your suggestion

**Comment by akaitoua** [comment]
@pp86, i checked your latest changes and everything works well. I will close this issue.
